src/Entity/Avis.php
<?php

namespace App\Entity;

use App\Repository\AvisRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AvisRepository::class)]
class Avis
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $commantaire = null;

    #[ORM\Column]
    private ?int $note = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\Column(length: 255)]
    private ?string $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCommantaire(): ?string
    {
        return $this->commantaire;
    }

    public function setCommantaire(string $commantaire): static
    {
        $this->commantaire = $commantaire;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChambreRepository::class)]
class Chambre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $description_courte = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_longue = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\Column]
    private ?int $prix_journalier = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'chambre', targetEntity: Commande::class, orphanRemoval: true)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescriptionCourte(): ?string
    {
        return $this->description_courte;
    }

    public function setDescriptionCourte(string $description_courte): static
    {
        $this->description_courte = $description_courte;

        return $this;
    }

    public function getDescriptionLongue(): ?string
    {
        return $this->description_longue;
    }

    public function setDescriptionLongue(string $description_longue): static
    {
        $this->description_longue = $description_longue;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): static
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setChambre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getChambre() === $this) {
                $commande->setChambre(null);
            }
        }

        return $this;
    }
}

templates/app/acces.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accès{% endblock %}

{% block body %}

	<link rel="stylesheet" href="./css/style.css">


<div class="bg-black bg-opacity-50 w-100 h-25 text-center position-absolute top-50 start-50 translate-middle">
    <h1 class="text-white mt-3">Nous rejoindre</h1>
    <p class="text-white-50 container">Accès et transport</p>
</div>

<div>
<img src="{{ asset('img/fixe/marseille.jpg') }}" class="d-block w-100" alt="">
</div>


<div class="container">
<div class="row my-4">
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d2905.5053128567347!2d5.372392521521978!3d43.26178850300185!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2sfr!4v1694161552577!5m2!1sfr!2sfr" width="640" height="480"></iframe>
</div>
</div>

{% endblock %}

templates/app/actualites.html.twig
{% extends 'base.html.twig' %}

{% block title %}Actualités{% endblock %}

{% block body %}

	<link rel="stylesheet" href="./css/style.css">


<h1 class="text-center my-4">Actualités</h1>

{% endblock %}

templates/app/avis.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les avis{% endblock %}

{% block body %}

<h1 class="text-center my-4">Les avis</h1>
<div class="container">
<a href="{{ path('app_avis_commentaire') }}" class="btn btn-primary">Poster un avis</a>
{% for avi in avis %}
    
<div class="card my-3">
  <h5 class="card-header">{{ avi.prenom }} {{ avi.nom }}</h5>
  <div class="card-body">
    <h5 class="card-title">Catégorie : {{ avi.category }}</h5>
    <p class="card-text">{{ avi.commantaire }}</p>
    <p class="card-text">Note :
    {% if avi.note == 0 %}
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
    {% elseif avi.note == 1 %}
<i class="bi bi-star-fill"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
    {% elseif avi.note == 2 %}
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
    {% elseif avi.note == 3 %}
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star"></i>
<i class="bi bi-star"></i>
    {% elseif avi.note == 4 %}
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star"></i>
    {% elseif avi.note == 5 %}
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
<i class="bi bi-star-fill"></i>
    {% endif %}  
    </p>
    <p class="card-text">Posté le {{ avi.dateEnregistrement|date('d/m/Y à H:i:s') }}</p>
  </div>
</div>
{% endfor %}
</div>

{% endblock %}

templates/app/chambres.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos chambres{% endblock %}

{% block body %}

<h1 class="text-center my-4">Nos chambres</h1>

<div class="container">
<section class="row justify-content-around">
{% for chambre in chambres %}
<div class="mb-3 col-3">
  <h3 class="card-header my-3">{{ chambre.titre }}</h3>
<img src="{{ asset('img/upload/'~ chambre.photo) }}" class="d-block w-100" alt="...">
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><span class="text-dark-50">Prix par nuit : </span>{{ chambre.prixJournalier }} €</li>
    <li class="list-group-item">{{ chambre.descriptionCourte }}</li>
  </ul>
  <div class="card-body text-center mt-3">
    <a href="{{ path('app_chambre_commande', {id: chambre.id}) }}" class="btn btn-primary">Voir plus</a>
  </div>
</div>

    
{% endfor %}
</section>
</div>

{% endblock %}

templates/app/commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation{% endblock %}

{% block body %}

<div class="container mt-4">
<div class=" mb-3">
  <h3 class="card-header">{{ chambre.titre }}</h3>
<img src="{{ asset('img/upload/'~ chambre.photo) }}" class="d-block w-100" alt="...">
  
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Prix par nuit : {{ chambre.prixJournalier }} €</li>
    <li class="list-group-item">{{ chambre.descriptionLongue|raw }}</li>
  </ul>
</div>
</div>

<div class="container my-4">
    {{ form_errors(commande) }}

    {{ form_start(commande) }}
    <div class="row">
    <div class="col-6">{{ form_row(commande.prenom) }}</div>
    <div class="col-6">{{ form_row(commande.nom) }}</div>
    <div class="col-6">{{ form_row(commande.telephone) }}</div>      
    <div class="col-6">{{ form_row(commande.email) }}</div>      
    <div class="col-6">{{ form_row(commande.date_arrivee) }}</div>
    <div class="col-6">{{ form_row(commande.date_depart) }}</div>
    </div>       
        <button type="submit" class="btn btn-primary">Réserver</button>
    {{ form_end(commande) }}
</div>


{% endblock %}

templates/app/commentaire.html.twig
{% extends 'base.html.twig' %}


{% block title %}Votre commentaire{% endblock %}

{% block body %}
        <link rel="stylesheet" href="./css/style.css">

<h1 class="text-center my-4">Votre commentaire</h1>
<div class="container">
{{ form_start(form) }}
<div class="row">
    {{ form_row(form.nom) }}
    {{ form_row(form.prenom) }}
    {{ form_row(form.note) }}
    {{ form_row(form.commantaire) }}
    {{ form_row(form.category) }}
</div>
<button type="submit" class="btn btn-primary my-4">Valider</button>
{{ form_end(form) }}
</div>

{% endblock %}

templates/app/conditions.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conditions Générales de Vente{% endblock %}

{% block body %}
	<link rel="stylesheet" href="./css/style.css">


<h1 class="text-center my-4">Conditions Générales de Vente</h1>



{% endblock %}

templates/app/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact{% endblock %}

{% block body %}

	<link rel="stylesheet" href="./css/style.css">


<h1 class="text-center my-4">Contact</h1>

<div class="container">
<form>
  <fieldset> 
  <div class="row">
    <div class="form-group col-6">
      <label for="nom" class="form-label mt-4">Nom</label>
      <input type="text" class="form-control" id="nom" placeholder="Nom">
    </div>
    <div class="form-group col-6">
      <label for="prenom" class="form-label mt-4">Prénom</label>
      <input type="text" class="form-control" id="prenom" placeholder="Prénom">
    </div>
  </div>
    <div class="form-group">
      <label for="email" class="form-label mt-4">Adresse mail</label>
      <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Adresse mail">
    </div>
    <div class="form-group">
      <label for="exampleSelect1" class="form-label mt-4">Catégorie</label>
      <select class="form-select" id="exampleSelect1">
        <option>Chambre</option>
        <option>Restaurant</option>
        <option>Spa</option>
        <option>Sujet général</option>
      </select>
    </div>
    <div class="form-group">
      <label for="exampleTextarea" class="form-label mt-4">Message</label>
      <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
    </div>   
    <button type="submit" class="btn btn-primary my-3">Envoyer</button>
  </fieldset>
</form>
</div>

{% endblock %}

templates/app/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hotel House{% endblock %}

{% block body %}

<div id="carouselExampleAutoplaying" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-inner">
  {% for slider in sliders %}  
        <div class="carousel-item {% if slider.ordre == 1 %} active {% endif %}">
      <img src="{{ asset('img/upload/' ~ slider.photo) }}" class="d-block w-100" alt="...">
    </div>    
  {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
  </button>
</div>

<section class="container my-5">
<div class="row row-cols-1 row-cols-md-4 g-4 justify-content-around">
  <div class="col">
    <div class="h-100">
      <img src="{{ asset('img/fixe/chambrecircle.jpg') }}" class="card-img-top rounded-circle" alt="...">
      <div class="card-body">
        <h3 class="card-title my-4 text-center fw-bold">Nos Chambres</h3>
        <p class="card-text my-4">Réveillez-vous dans le confort ultime, où chaque nuit devient une expérience de rêve. Notre chambre d'hôtel vous offre un havre de tranquillité et d'élégance, une escapade parfaite pour votre prochain séjour inoubliable.</p>
      </div>
      <div class="card-footer text-center">
        <a href="{{ path('app_chambre') }}" class="btn btn-primary">Voir plus</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="h-100">
      <img src="{{ asset('img/fixe/restaurantcircle.jpg') }}" class="card-img-top rounded-circle" alt="...">
      <div class="card-body">
        <h3 class="card-title my-4 text-center fw-bold">Notre Restaurant</h3>
        <p class="card-text my-4">Savourez l'excellence culinaire dans un cadre envoûtant, où chaque plat raconte une histoire de passion et de goût. Bienvenue chez nous, où chaque bouchée est une expérience inoubliable.</p>
      </div>
      <div class="card-footer text-center">
        <a href="{{ path('app_restaurant') }}" class="btn btn-primary">Voir plus</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="h-100">
      <img src="{{ asset('img/fixe/spacircle.jpg') }}" class="card-img-top rounded-circle" alt="...">
      <div class="card-body">
        <h3 class="card-title my-4 text-center fw-bold">Notre Spa</h3>
        <p class="card-text my-4">Plongez dans l'ultime oasis de bien-être et de détente. Notre spa vous offre une évasion totale du stress quotidien, un havre de sérénité où chaque soin vous rapproche de l'harmonie intérieure. Découvrez le paradis du bien-être avec nous.</p>
      </div>
      <div class="card-footer text-center">
        <a href="{{ path('app_spa') }}" class="btn btn-primary">Voir plus</a>
      </div>
    </div>
  </div>
</div>
</section>
{% endblock %}

templates/app/information.html.twig
{% extends 'base.html.twig' %}

{% block title %}Informations
{% endblock %}

{% block body %}
	<link rel="stylesheet" href="./css/style.css">

	<h1 class="text-center my-4">Qui Sommes-Nous ?</h1>
	<div class="container">
		<div class="row my-4">
			<div class="col-7 gap-3">
				<p>Bienvenue à
					<strong class="fw-bold">Hotel House</strong>, votre refuge d'exception au cœur de
					<strong class="fw-bold">Marseille</strong>. Notre histoire est celle de l'excellence en matière d'hospitalité et de service personnalisé depuis
					<strong class="fw-bold">1990</strong>.</p>

				<div>
					<h3>Notre Histoire</h3>
					<p>Fondé par
						<strong class="fw-bold">Maxime Durand</strong>
						avec une vision de créer un lieu où le luxe et le confort se rencontrent,
						<strong class="fw-bold">Hotel House</strong>
						a rapidement gagné une réputation enviable dans l'industrie hôtelière. Depuis lors, notre établissement s'est développé pour devenir un pilier de l'hospitalité haut de gamme à
						<strong class="fw-bold">Marseille</strong>.</p>
				</div>

				<div>
					<h3>Notre Philosophie</h3>
					<p>Chez
						<strong class="fw-bold">Hotel House</strong>, nous croyons en l'art de faire de chaque séjour une expérience inoubliable. Nous mettons un point d'honneur à anticiper et à répondre à tous les besoins de nos clients avec grâce et professionnalisme. Notre engagement envers l'excellence transparaît dans chaque détail, de l'accueil chaleureux à l'élégance de nos chambres, en passant par notre cuisine raffinée.</p>
				</div>

				<div>
					<h3>Notre Équipe</h3>
					<p>Notre équipe dévouée et passionnée est le cœur de notre succès. Chacun de nos membres du personnel est formé à offrir un service exceptionnel, attentif à chaque demande, et dédié à rendre votre séjour mémorable.</p>
				</div>

				<div>
					<h3>Nos Installations</h3>
					<p>
						<strong class="fw-bold">Hotel House</strong>
						offre une gamme complète d'installations et de services pour répondre à tous vos besoins, que ce soit pour les voyages d'affaires ou les escapades romantiques. De nos chambres luxueuses à notre restaurant gastronomique, de notre spa apaisant à nos espaces de réunion bien équipés, nous avons tout ce dont vous avez besoin pour un séjour parfait.</p>
				</div>

				<div>
					<h3>Notre Engagement envers l'Environnement
					</h3>
					<p>Chez
						<strong class="fw-bold">Hotel House</strong>, nous sommes soucieux de l'environnement. Nous avons mis en place des pratiques durables pour minimiser notre empreinte écologique et contribuer à la préservation de notre planète.</p>

					<p>Nous sommes fiers de vous accueillir à
						<strong class="fw-bold">Hotel House</strong>
						et nous nous engageons à vous offrir une expérience inoubliable à chaque visite. Merci de nous faire confiance pour vos voyages et vos moments précieux. Nous avons hâte de vous accueillir chez nous.</p>
					<p>N'hésitez pas à nous contacter pour toute demande ou réservation.</p>
				</div>

			</div>
			<div class="col-5">

				<img src="{{ asset('img/fixe/hotel.jpg') }}" alt="" style="width: 28rem;" class="">
			</div>
		</div>
	</div>


{% endblock %}

templates/app/mentionlegales.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mention Légales{% endblock %}

{% block body %}
	<link rel="stylesheet" href="./css/style.css">


<h1 class="text-center my-4">Mention Légales</h1>

<div class="container">
    <div class="col-8">
    <div class="row my-4 gap-3">
        <div>
            <h2>Propriété intellectuelle</h2>
            <p>L'ensemble du contenu de ce site web, y compris les textes, les images, les vidéos, les graphiques et les logos, est la propriété exclusive de <strong class="fw-bold">Hotel House</strong> ou de ses partenaires et est protégé par les lois sur la propriété intellectuelle en vigueur. Toute utilisation, reproduction ou distribution non autorisée du contenu de ce site est strictement interdite.</p>
        </div>
        <div>
            <h2>Données personnelles</h2>
            <p>Les informations collectées sur ce site web sont soumises à notre politique de confidentialité. En utilisant ce site, vous consentez à la collecte, au traitement et à l'utilisation de vos données personnelles conformément à cette politique.</p>
        </div>
        <div>
            <h2>Cookies</h2>
            <p>Ce site web utilise des cookies pour améliorer l'expérience de l'utilisateur. Vous pouvez en savoir plus sur l'utilisation des cookies dans notre politique de cookies, disponible à l'adresse [Insérer le lien vers la politique de cookies].</p>
        </div>
        <div>
            <h2>Responsabilité</h2>
            <p><strong class="fw-bold">Hotel House</strong> s'efforce de fournir des informations précises et à jour sur ce site web, mais ne peut garantir l'exactitude ou l'exhaustivité de ces informations. En conséquence, <strong class="fw-bold">Hotel House</strong> décline toute responsabilité pour tout préjudice résultant de l'utilisation de ce site web.</p>
        </div>
        <div>
            <h2>Droit applicable et juridiction compétente</h2>
            <p>Les présentes mentions légales sont régies par le droit en France. En cas de litige, les tribunaux de <strong class="fw-bold">Marseille</strong> seront compétents.</p>
        </div>

    </div>
    </div>
</div>

{% endblock %}

templates/app/plan.html.twig
{% extends 'base.html.twig' %}

{% block title %}Plan du site{% endblock %}

{% block body %}
	<link rel="stylesheet" href="./css/style.css">


<h1 class="text-center my-4">Plan du site</h1>



{% endblock %}

templates/app/restaurant.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurant{% endblock %}

{% block body %}

	{# <link rel="stylesheet" href="./css/style.css"> #}


<div class="bg-black bg-opacity-50 w-100 h-25 text-center position-absolute top-50 start-50 translate-middle">
    <h1 class="text-white mt-3">Notre Restaurant</h1>
    <p class="text-white-50 container">Savourez l'excellence culinaire dans un cadre envoûtant, où chaque plat raconte une histoire de passion et de goût. Bienvenue chez nous, où chaque bouchée est une expérience inoubliable.</p>
</div>

<div>
    <img src="{{ asset('img/fixe/restaurant.jpg') }}" class="d-block w-100" alt="...">
</div>

<div class="container">
    <div class="row">
            <h2 class="my-4">Menu</h2>
        <div class="my-4 col-6">

            <div>
                <h3>Entrées</h3>
            <ul>
                <li><strong class="fw-bold">Salade César </strong>: Laitue romaine, croûtons à l'ail, parmesan, sauce Caesar : 9 €</li>
                <li><strong class="fw-bold">Velouté de Champignons </strong>: Crème fraîche, herbes fraîches : 8 €</li>
                <li><strong class="fw-bold">Carpaccio de Bœuf </strong>: Filet de bœuf, roquette, copeaux de parmesan : 12 €</li>
            </ul>
            </div>
            <div>
                <h3>Plats Principaux</h3>
                <ul>
                    <li><strong class="fw-bold">Filet de Saumon Grillé </strong>: Sauce au citron, purée de pommes de terre, légumes de saison : 18 €</li>
                    <li><strong class="fw-bold">Risotto aux Champignons Sauvages </strong>: Parmesan, truffe noire : 16 €</li>
                    <li><strong class="fw-bold">Entrecôte Grillée </strong>: Frites maison, sauce béarnaise : 24 €</li>
                </ul>
            </div>
            <div>
                <h3>Spécialités du Chef</h3>
                <ul>
                    <li><strong class="fw-bold">Poulet à la Provençale </strong>: Tomates, olives, herbes de Provence, riz basmati : 17 €</li>
                    <li><strong class="fw-bold">Pâtes Fraîches au Homard </strong>: Sauce au beurre d'ail, persil frais : 28 €</li>
                    <li><strong class="fw-bold">Médaillon de Veau aux Morilles </strong>: Pommes de terre sautées, sauce aux morilles : 26 €</li>
                </ul>
            </div>
            <div>
                <h3>Desserts</h3>
                <ul>
                    <li><strong class="fw-bold">Tiramisu Maison </strong>: Café, mascarpone, cacao : 7 €</li>
                    <li><strong class="fw-bold">Fondant au Chocolat </strong>: Glace à la vanille, coulis de framboises : 8 €</li>
                    <li><strong class="fw-bold">Crème Brûlée </strong>: Vanille de Madagascar : 7 €</li>
                </ul>
            </div>
            <div>
                <h3>Boissons</h3>
                <ul>
                    <li>Eaux minérales, sodas, jus de fruits, café, thé, et une sélection de vins sont disponibles.</li>

                </ul>
            </div>
            <div>
                <h3>Horaires d'ouverture</h3>
                <ul>
                    <li><strong class="fw-bold">Lundi à Vendredi </strong>: 12h00 - 14h30, 19h00 - 22h30</li>
                    <li><strong class="fw-bold">Samedi et Dimanche </strong>: 19h00 - 22h30</li>
                </ul>
            </div>
        </div>
        <div class="col-6">
            <div class="row justify-content-end">
                <img src="{{ asset('img/fixe/salade.jpg')}}" class="w-75 my-4" alt="">
                <img src="{{ asset('img/fixe/entrecote.jpg')}}" class="w-75 my-4" alt="">
            </div>
        
        </div>

    </div>

</div>

{% endblock %}